### ISSUE TITLE
Use MapBox Draw function in AirMap

### ISSUE THREAD

**Issue by KumarAniket** [airmap/js-map-sdk#25]
I wanted to use the mapbox draw function with AirMap. Please let me know how to do so.

**Comment by f2m2rd** [comment]
See https://www.mapbox.com/mapbox-gl-js for information on using Mapbox.

**Comment by KumarAniket** [comment]
It is for mapbox-gl and I want to use it with js-airmap-sdk

**Comment by f2m2rd** [comment]
This SDK will be deprecated this week. Please use: https://developers.airmap.com/v2.1/docs/contextual-airspace-plugin
