### ISSUE TITLE
Use mapboxgl feature with js-map-sdk

### ISSUE THREAD

**Issue by KumarAniket** [airmap/js-map-sdk#26]
I want to use the draw polygon feature of mapboxgl with js-map-sdk. The draw polygon feature is not wrapped in the js-map-sdk. So, I need an example of how to access the draw polygon feature of mapboxgl in js-map-sdk.

Please mention an example how to use.

**Comment by f2m2rd** [comment]
You should be able to use the mapbox example code with the js map SDK plug-in.

 We are getting ready to release a new plug-in that supports contextual airspsce
